cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('delete/<int:product_id>/',views.cart_delete,name='cart_delete'),
    path('',views.cart_detail,name='cart_detail'),
]

ecommerseproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
]
urlpatterns = urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('search/', views.search_product, name='search-product'),
    path('',views.allproduct,name='allproduct'),
    path('<slug:c_slug>/',views.allproduct, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.productdetail, name='product_detail'),
]

cart/models.py
from django.db import models
from shop.models import Product,Category 
# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=300,blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering =['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)
    
class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'
    
    def sub_total(self):
        return self.product.price * self.quantity
    
    def __str__(self):
       return '{}'.format(self.product)

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=300,unique=True)
    slug = models.SlugField(max_length=300,unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])

    def __str__(self):
        return self.name
    
    
class Product(models.Model):
    name = models.CharField(max_length=300,unique=True)
    slug = models.SlugField(max_length=300,unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product',blank=True)
    stock = models.IntegerField()
    avilable = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    
    def get_url(self):
        return reverse('shop:product_detail',args=[self.category.slug,self.slug])
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name

cart/views.py
from django.shortcuts import render,redirect
from shop.models import Product,Category
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render,get_object_or_404
# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product,cart=cart)
        if (cart_item.quantity < cart_item.product.stock):
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = product,
            quantity = 1,
            cart = cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')



def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def cart_delete(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

    
def cart_detail(request,total=0,counter=0,cart_item=None):
    try:
        cart = Cart.objects.get(cart_id= _cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price * cart_item.quantity)
            counter +=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',{'cart_items':cart_items,'total':total,'counter':counter})

shop/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage  # Paginator

from django.db.models import Q    # Search

# Create your views here.


def allproduct(request,c_slug=None):
    c_page = None
    roducts_list = None

    if c_slug!= None:
        c_page = get_object_or_404(Category,slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page,avilable=True)
    else:
        products_list = Product.objects.all().filter(avilable=True)
    paginator = Paginator(products_list,8)
    try:
        page_number = request.GET.get('page') 
    except:
        page_number =1 
    try:
        products = paginator.page(page_number)
    except (EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request,"category.html",{'category':c_page,'products':products,'categ':products_list})

def productdetail(request,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

def search_product(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        products = Product.objects.filter(Q(name__contains=searched)|Q(category__name__contains=searched)|Q(description__contains=searched)|Q(price__contains=searched))

        return render(request, 'search.html', {'searched': searched, 'products': products})
    else:
        return render(request, 'search.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block metadescription %} {% endblock %}">

    <title>{% block title %}  {% endblock %}</title>
<!------------------------------------ Bootstrap css link ----------------------------------->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<!--------------------------------Bootstrap css local link ----------------------------------->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

<!--------------------------------- Google fonts ---------------------------------------------->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

</head>
<body>
    <div>
        {% include 'header.html' %}
        {% include 'navbar.html' %}

        {% block content %}

        {% endblock %}
    </div>

    
    {% include 'footer.html' %}

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://kit.fontawesome.com/7aca34b55f.js" crossorigin="anonymous"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is cart  page proceed to review your items and place the order
{% endblock %}

{% block title %}
    Food Shop Company
{% endblock %}

{% block content %}
{% if not cart_items %}
    <div class="container">
        <div class="row">
            <div class="col-md-12 txt1">
                <h1 class="mb-4">Your cart page is empty</h1><br>
                <p class="text-center">Click <a href="{% url 'shop:allproduct' %}">Here</a> to continue shoping</p>
            </div>
        </div>
    </div>
{% else %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-12 carthead txt4 mb-5">
                        <h4 class="">Your cart items</h4>
                    </div>
                    {% for cart_item in cart_items %}
                    <div class="col-md-4 mb-4 cartimgstyle">
                        <a href="{{ cart_item.product.get_url }}"><img src="{{ cart_item.product.image.url }}" alt="image"></a>
                    </div>
                    <div class="col-md-4 mb-4">
                        <div class="row productalignment">
                            <div class="col-12 txt3">
                                <h5>{{ cart_item.product.name }}</h5>
                            </div>
                            <div class="col-12 txt3">
                                <h6 class="text-muted">Price : {{ cart_item.product.price }}₹</h6>
                            </div>
                            <div class="col-12 txt3">
                                <h6 class="text-muted">Qty : {{ cart_item.quantity }} x {{ cart_item.product.price }}₹</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2 mb-4 txt3 txt2">
                        <h6>Total: {{ cart_item.sub_total }}₹</h6>
                    </div>
                    <div class="col-md-2 mb-4">
                        <div class="row">
                            {% if cart_item.quantity < cart_item.product.stock %}
                            <div class="col-12 iconcolor">
                                <a href="{% url 'cart:add_cart' cart_item.product.id %}"><i class="fa-solid fa-plus"></i></a>
                            </div>
                            <div class="col-12 iconcolor">
                                <a href="{% url 'cart:cart_remove' cart_item.product.id %}"><i class="fa-solid fa-minus"></i></a>
                            </div>
                            <div class="col-12 iconcolor">
                                <a href="{% url 'cart:cart_delete' cart_item.product.id %}"><i class="fa-solid fa-trash"></i></a>
                            </div>
                            {% else %}
                            <div class="col-12 iconcolor">
                                <a href="{% url 'cart:cart_remove' cart_item.product.id %}"><i class="fa-solid fa-minus"></i></a>
                            </div>
                            <div class="col-12 iconcolor">
                                <a href="{% url 'cart:cart_delete' cart_item.product.id %}"><i class="fa-solid fa-trash"></i></a>
                            </div>
                            {% endif %}
                        </div>
                    </div> <hr>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-6">
                <div class="row">       
                    <div class="col-12 carthead txt4 mb-5">
                        <h4>Checkout</h4>
                    </div>
                    <div class="col-12 txt1">
                        <div class="row">
                            <div class="col-12 txt1 text-center">
                                <p>Net amout is: <b>{{ total }}₹</b></p>
                            </div>
                            <div class="col-12 txt4 text-center">
                                <a class="btn btn-outline-secondary" href="{% url 'shop:allproduct' %}"><span style="padding-right: 10px;">Continue Shopping</span><i class="fa-solid fa-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endif %}
    {% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:150 }}
    {% else %}
        Welcome to my Store
    {% endif %}
{% endblock %}

{% block title %}
{% if category %}
    {{ category.name }}
{% else %}
    Our new collections
{% endif %}
{% endblock %}

{% block content %}

{% if category %}
<div class="container">
    <div class="row">
        <!-- <div class="col-12 producttimg">
            <img src="{{ category.image.url }}" alt="{{ category.name }}">
        </div> -->
        <div class="col-12 txt1 pb-2">
            <h1>{{ category.name }}</h1>
        </div>
        <div class="col-12 txt1 pb-3">
            <p>{{ category.description }}</p> 
        </div>
        {% for cat in categ %}
        <div class="col-md-3">
            <div class="row">
                <div class="col-12 prodimg">
                    <a href="{{ cat.get_url }}"><img src="{{ cat.image.url }}" alt="{{ cat.name }}"></a>                        
                </div>
                <div class="col-12 proddetail">
                    <div class="row">
                        <div class="col-md-12 pname">
                            <h6 class="">{{ cat.name }}</h6>
                        </div>
                        <div class="col-md-12 prate">
                            <p class="text-muted">{{ cat.price }}₹</p>
                        </div>
                    </div>
                </div>  
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12 homeimg">
            <img class="" src="{% static 'img/homeimg5.jpeg' %}" alt="Product">
            <div class="overlay-text">Food Shop</div>
        </div>
        <div class="col-12">
            <div class="row">
                <div class="col-12 txt1 mt-5">
                    <h1>Our products collections</h1>
                </div>
                <div class="col-12 txt2 mt-3">
                    <p>It is a long established fact that a reader will be distracted by the readable content oa page when looking at its layout. The point of using Lorem Ipsum is that it has more-or-less normal distribution of letters, as opposed to using 'Content here, contenhere', making it look like readable English. Many desktop publishing packages and web pageditors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' wiluncover many web sites still in their infancy.</p>
                </div>
            </div>
        </div>
        
        <div class="col-12 productalignment">
            <div class="row ">
                {% for product in products.object_list %}
                <div class="col-md-3">
                    <div class="row">
                        <div class="col-12 prodimg">
                            <a href="{{ product.get_url }}"><img src="{{ product.image.url }}" alt="{{ product.name }}"></a>                        
                        </div>
                        <div class="col-12 proddetail">
                            <div class="row">
                                <div class="col-md-12 pname">
                                    <h6 class="">{{ product.name }}</h6>
                                </div>
                                <div class="col-md-12 prate">
                                    <p class="text-muted">{{ product.price }}₹</p>
                                </div>
                            </div>
                        </div>  
                    </div>
                </div>
                {% endfor %}
            </div>
        </div><br>
    </div> 

    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %} 
    </div>
</div>

{% endif %}

{% endblock %}

templates/footer.html
{% load static %}

<footer>
    <div class="footstyle">
        <center>
             <p class="mb-0">This is footer section</p>
        </center>
    </div>
</footer>

templates/header.html
{% load static %}
<header>
    <center>
        <div class=" col-md-2 logoimg">
            <img src="{% static 'img/ONLINE SHOP.png' %}" alt="logoimage">
        </div>
    </center>
</header>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Hello world
</body>
</html>

templates/navbar.html
{% load static %}

  <div class="container-fluid  mb-5">
        <nav class="navbar navbar-expand-lg navbar-light nav-custom ">
        <div class="divpos">
            <i class="fa-solid fa-shop"></i>
       </div>
       <div class="divpos">
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
      </div>
       <div class="collapse navbar-collapse divpos " id="navbarNavDropdown">
         <ul class="navbar-nav">
           <li class="nav-item active">
             <a class="nav-link" href="{% url 'shop:allproduct' %}">Home<span class="sr-only">(current)</span></a>
           </li>
           <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Category
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'shop:allproduct' %}">All Product</a></li>
                {% for i in link %}
                <li><a href="{{ i.get_url }}">{{ i.name }}</a></li>
                {% endfor %}
            </ul>
          </li>
          {% if item_count > 0 %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i><sup><b><span style="color:red;">( {{ item_count }} )</span></b></sup></a>
          </li>
          {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i></a>
          </li>
          {% endif %}
         </ul>
       </div>

       <div class="navbar navbar-light search-custom">
        <form class="form-inline" method="post" action="{% url 'shop:search-product' %}" enctype="multipart/form-data">

            {% csrf_token %}

           <div class="row">
             <div class="col-10 pr-2 border-right-0">
               <input class="form-control pl-0" type="search" placeholder="Search product" aria-label="Search" name="searched">
             </div>
             <div class="col-2 pl-2 pt-2 border-left-0">
              <button class="" type="submit">
                <i class="fa-solid fa-magnifying-glass"></i>
              </button>
             </div>
           </div>
        </form>
      </div>
    </nav>
  </div>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    {{ productt.description|truncatewords:150 }}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <p><a href="{% url 'shop:allproduct' %}">Home</a> -> <a href="{{ product.category.get_url }}">{{ product.category }} -> {{ product.name }}</a></p>
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-12 producttimg">
                    <img src="{{ product.image.url }}" alt="{{ product.name }}">                
                </div>
                <div class="col-12 producttdet">
                    <div class="row">
                        <div class="col-md-12 pdname">
                            <h6 class="">{{ product.name }}</h6>
                        </div>
                        <div class="col-md-12 pdrate">
                            <p class="text-muted">{{ product.price }}₹</p>
                        </div>
                        <div class="col-12 pdcart">
                            {% if prodcut.stock <= 0 %}
                            <p><b>Out Of Stock</b></p>
                            {% else %}
                            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
                            {% endif %}
                        </div>
                    </div>
                </div> 
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-12 txt3">
                   <h3>{{ product.name }}</h3> 
                </div>
                <div class="col-md-12 txt3">
                    <p>Price: <b>{{ product.price }}₹</b></p>
                </div>
                <div class="col-md-12 txt3">
                    <h5 class="text-muted">Product Descripion</h5>
                    <p>{{ product.description }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:150 }}
    {% else %}
        Welcome to my Store
    {% endif %}
{% endblock %}

{% block title %}
{% if category %}
    {{ category.name }}
{% else %}
    Our new collections
{% endif %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12 itemcenter">
            <div class="row ">
                {% if searched %}
                    <div class="col-12 mb-5 text-center">
                        <h5>You searched for <b>{{searched}}</b>...</h5>
                    </div>
                    {% for product in products %}
                        <div class="col-md-2 searchimg txt3">
                            <a href="{{ product.get_url }}"><img src="{{ product.image.url }}" alt="PorductImage"></a>
                            <h6 class="text-center">{{product.name}}</h6>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="nothing">
                        <h3 class="text-center">Nothing found</h3>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}